server:
  port: 8080
spring:
  application:
    name: grove-cache-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
