spring:
  application:
    name: weavy

server:
  port: 8084

openai:
  api-key: ${OPENAI_API_KEY:sk-proj-1234}

milvus:
  uri: ${MILVUS_URI:http://127.0.0.1:19530}
  collection: ${MILVUS_COLLECTION:weavy_test}
  dimension: ${MILVUS_DIMENSION:1536}

ratelimit:
  perIp:
    daily: 50
  timezone: "Asia/Seoul"
