server:
  port: 8081

spring:
  application:
    name: grove-task-mixture-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

milvus:
  host: ${MILVUS_HOST:localhost}
  port: ${MILVUS_PORT:19530}
  database: default
  collection-name:
    instruction-alpaca: instruction_alpaca
    seed-sentence: seed_sentence
